/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppingcart;

import javax.swing.JOptionPane;


public class loginpage extends javax.swing.JFrame {

    userlogin ul = userlogin.getInstance();
    
    public loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperpanel = new javax.swing.JPanel();
        usersigninbtn = new javax.swing.JButton();
        signupbtn = new javax.swing.JButton();
        adminsigninbtn = new javax.swing.JButton();
        lowerpanel = new javax.swing.JPanel();
        usersigninpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        userpassfield = new javax.swing.JPasswordField();
        usersigninbtn1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        signuppanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernamesignupfield = new javax.swing.JTextField();
        userpasssignupfield = new javax.swing.JPasswordField();
        emailfield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        signupbtn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adminsigninpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adminnamefield = new javax.swing.JTextField();
        adminpassfield = new javax.swing.JPasswordField();
        adminsigninbtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upperpanel.setBackground(new java.awt.Color(204, 204, 204));
        upperpanel.setForeground(new java.awt.Color(51, 51, 51));

        usersigninbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usersigninbtn.setText("Sign In");
        usersigninbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersigninbtnActionPerformed(evt);
            }
        });

        signupbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        signupbtn.setText("Sign Up");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });

        adminsigninbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adminsigninbtn.setText("Admin");
        adminsigninbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsigninbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperpanelLayout = new javax.swing.GroupLayout(upperpanel);
        upperpanel.setLayout(upperpanelLayout);
        upperpanelLayout.setHorizontalGroup(
            upperpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperpanelLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(usersigninbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminsigninbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        upperpanelLayout.setVerticalGroup(
            upperpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperpanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(upperpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usersigninbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminsigninbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(upperpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 120));

        lowerpanel.setBackground(new java.awt.Color(255, 255, 255));
        lowerpanel.setForeground(new java.awt.Color(255, 255, 255));
        lowerpanel.setLayout(new java.awt.CardLayout());

        usersigninpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\programs\\projects\\ShoppingCart\\src\\images\\userlogin.PNG")); // NOI18N

        usernamefield.setBackground(new java.awt.Color(102, 102, 102));
        usernamefield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernamefield.setForeground(new java.awt.Color(204, 204, 204));
        usernamefield.setText("Enter username");
        usernamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernamefieldFocusGained(evt);
            }
        });

        userpassfield.setBackground(new java.awt.Color(102, 102, 102));
        userpassfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userpassfield.setForeground(new java.awt.Color(204, 204, 204));
        userpassfield.setText("jPasswordField1");
        userpassfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userpassfieldFocusGained(evt);
            }
        });

        usersigninbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usersigninbtn1.setText("Sign In");
        usersigninbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersigninbtn1ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("----------------------------------------");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Sign In");

        javax.swing.GroupLayout usersigninpanelLayout = new javax.swing.GroupLayout(usersigninpanel);
        usersigninpanel.setLayout(usersigninpanelLayout);
        usersigninpanelLayout.setHorizontalGroup(
            usersigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersigninpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(usersigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersigninpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(usersigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernamefield)
                                .addComponent(userpassfield, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersigninpanelLayout.createSequentialGroup()
                                .addComponent(usersigninbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)))
                        .addGap(58, 58, 58))
                    .addGroup(usersigninpanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(usersigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        usersigninpanelLayout.setVerticalGroup(
            usersigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersigninpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersigninpanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(userpassfield, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(usersigninbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        lowerpanel.add(usersigninpanel, "card2");

        signuppanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\programs\\projects\\ShoppingCart\\src\\images\\signup.PNG")); // NOI18N

        usernamesignupfield.setBackground(new java.awt.Color(102, 102, 102));
        usernamesignupfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernamesignupfield.setForeground(new java.awt.Color(204, 204, 204));
        usernamesignupfield.setText("Enter Username");
        usernamesignupfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernamesignupfieldFocusGained(evt);
            }
        });

        userpasssignupfield.setBackground(new java.awt.Color(102, 102, 102));
        userpasssignupfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userpasssignupfield.setForeground(new java.awt.Color(204, 204, 204));
        userpasssignupfield.setText("jPasswordField1");
        userpasssignupfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userpasssignupfieldFocusGained(evt);
            }
        });

        emailfield.setBackground(new java.awt.Color(102, 102, 102));
        emailfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailfield.setForeground(new java.awt.Color(204, 204, 204));
        emailfield.setText("Enter Email");
        emailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfieldFocusGained(evt);
            }
        });

        contactfield.setBackground(new java.awt.Color(102, 102, 102));
        contactfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactfield.setForeground(new java.awt.Color(204, 204, 204));
        contactfield.setText("Enter Contact");
        contactfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactfieldFocusGained(evt);
            }
        });

        signupbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signupbtn1.setText("Sign Up");
        signupbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtn1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Sign Up");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("----------------------------------------");

        javax.swing.GroupLayout signuppanelLayout = new javax.swing.GroupLayout(signuppanel);
        signuppanel.setLayout(signuppanelLayout);
        signuppanelLayout.setHorizontalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signuppanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernamesignupfield)
                                .addComponent(userpasssignupfield)
                                .addComponent(emailfield)
                                .addComponent(contactfield, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(signupbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)))
                        .addGap(48, 48, 48))
                    .addGroup(signuppanelLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        signuppanelLayout.setVerticalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(usernamesignupfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(userpasssignupfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(contactfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(signupbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        lowerpanel.add(signuppanel, "card3");

        adminsigninpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\programs\\projects\\ShoppingCart\\src\\images\\adminlogin.PNG")); // NOI18N

        adminnamefield.setBackground(new java.awt.Color(102, 102, 102));
        adminnamefield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminnamefield.setForeground(new java.awt.Color(204, 204, 204));
        adminnamefield.setText("Enter Username");
        adminnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminnamefieldFocusGained(evt);
            }
        });

        adminpassfield.setBackground(new java.awt.Color(102, 102, 102));
        adminpassfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminpassfield.setForeground(new java.awt.Color(204, 204, 204));
        adminpassfield.setText("jPasswordField1");
        adminpassfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminpassfieldFocusGained(evt);
            }
        });

        adminsigninbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminsigninbtn1.setText("Sign In");
        adminsigninbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsigninbtn1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Admin");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("----------------------------------");

        javax.swing.GroupLayout adminsigninpanelLayout = new javax.swing.GroupLayout(adminsigninpanel);
        adminsigninpanel.setLayout(adminsigninpanelLayout);
        adminsigninpanelLayout.setHorizontalGroup(
            adminsigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminsigninpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(adminsigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminsigninpanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(adminsigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminsigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(adminnamefield)
                                .addComponent(adminpassfield, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminsigninpanelLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(adminsigninbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(adminsigninpanelLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(adminsigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        adminsigninpanelLayout.setVerticalGroup(
            adminsigninpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminsigninpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminsigninpanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(adminpassfield, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(adminsigninbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );

        lowerpanel.add(adminsigninpanel, "card4");

        getContentPane().add(lowerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1290, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamefieldFocusGained
        // TODO add your handling code here:
        usernamefield.setText("");
        
    }//GEN-LAST:event_usernamefieldFocusGained

    private void userpassfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userpassfieldFocusGained
        // TODO add your handling code here:
        userpassfield.setText("");
    }//GEN-LAST:event_userpassfieldFocusGained

    private void usernamesignupfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamesignupfieldFocusGained
        // TODO add your handling code here:
        usernamesignupfield.setText("");
    }//GEN-LAST:event_usernamesignupfieldFocusGained

    private void userpasssignupfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userpasssignupfieldFocusGained
        // TODO add your handling code here:
        userpasssignupfield.setText("");
    }//GEN-LAST:event_userpasssignupfieldFocusGained

    private void emailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusGained
        // TODO add your handling code here:
        emailfield.setText("");
    }//GEN-LAST:event_emailfieldFocusGained

    private void contactfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusGained
        // TODO add your handling code here:
        contactfield.setText("");
    }//GEN-LAST:event_contactfieldFocusGained

    private void adminnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminnamefieldFocusGained
        // TODO add your handling code here:
        adminnamefield.setText("");
    }//GEN-LAST:event_adminnamefieldFocusGained

    private void adminpassfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminpassfieldFocusGained
        // TODO add your handling code here:
        adminpassfield.setText("");
    }//GEN-LAST:event_adminpassfieldFocusGained

    private void usersigninbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersigninbtnActionPerformed
        // TODO add your handling code here:
        usersigninpanel.setVisible(true);
        signuppanel.setVisible(false);
        adminsigninpanel.setVisible(false);
    }//GEN-LAST:event_usersigninbtnActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        usersigninpanel.setVisible(false);
        signuppanel.setVisible(true);
        adminsigninpanel.setVisible(false);
    }//GEN-LAST:event_signupbtnActionPerformed

    private void adminsigninbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsigninbtnActionPerformed
        // TODO add your handling code here:
        usersigninpanel.setVisible(false);
        signuppanel.setVisible(false);
        adminsigninpanel.setVisible(true);
    }//GEN-LAST:event_adminsigninbtnActionPerformed

    private void usersigninbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersigninbtn1ActionPerformed
        // TODO add your handling code here:
          if(ul.signIn(usernamefield.getText(), userpassfield.getText())){
              
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Please try again");
                usernamefield.setText("");
                userpassfield.setText("");
            }
    }//GEN-LAST:event_usersigninbtn1ActionPerformed

    private void signupbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtn1ActionPerformed
        // TODO add your handling code here:
       
        if(usernamesignupfield.getText().equalsIgnoreCase("enter username") || usernamesignupfield.getText().equalsIgnoreCase("")
                && emailfield.getText().equalsIgnoreCase("enter email") || 
                emailfield.getText().equalsIgnoreCase("") && contactfield.getText().equalsIgnoreCase("enter contact") || 
                contactfield.getText().equalsIgnoreCase("")){
                        JOptionPane.showMessageDialog(null, "Please Enter all required fields");
        
        }else{
            ul.registration(usernamesignupfield.getText(), userpasssignupfield.getText(), emailfield.getText(),
                contactfield.getText());
            usersigninpanel.setVisible(true);
            signuppanel.setVisible(false);
            adminsigninpanel.setVisible(false);
        }
    }//GEN-LAST:event_signupbtn1ActionPerformed

    private void adminsigninbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsigninbtn1ActionPerformed
        // TODO add your handling code here:
        AbstractAdmin admin = AdminFactory.getAdmin(adminnamefield.getText(), adminpassfield.getText());
            if(admin.isNil()){
                JOptionPane.showMessageDialog(null, "Invalid username or password");
                adminnamefield.setText("");
                adminpassfield.setText("");
            }else{
                dispose();
                AdminPanel ap = new AdminPanel();
                ap.setVisible(true);
            }
    }//GEN-LAST:event_adminsigninbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminnamefield;
    private javax.swing.JPasswordField adminpassfield;
    private javax.swing.JButton adminsigninbtn;
    private javax.swing.JButton adminsigninbtn1;
    private javax.swing.JPanel adminsigninpanel;
    private javax.swing.JTextField contactfield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel lowerpanel;
    private javax.swing.JButton signupbtn;
    private javax.swing.JButton signupbtn1;
    private javax.swing.JPanel signuppanel;
    private javax.swing.JPanel upperpanel;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JTextField usernamesignupfield;
    private javax.swing.JPasswordField userpassfield;
    private javax.swing.JPasswordField userpasssignupfield;
    private javax.swing.JButton usersigninbtn;
    private javax.swing.JButton usersigninbtn1;
    private javax.swing.JPanel usersigninpanel;
    // End of variables declaration//GEN-END:variables
}
